### PR TITLE
Update new-note

### PR DESCRIPTION
**Pull request by SylvesterWilmott**
## Fix

This PR updates the new-note icon to one with a clearer visual center.

Screenshot 2021-06-21 at 13 16 14

## To Test

- Verify the icon appears as intended on a 24px grid.
- Verify the SVG code is consistent with other icons.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Looks great overall @SylvesterWilmott! One tiny suggestion: I think we might be able to get the "pencil" part of the icon aligned more tightly to the gridlines, like so (current icon left, and on the left is refined to the 2px gridline):

<a href="https://user-images.githubusercontent.com/1200432/123008562-b3c15a80-d380-11eb-850f-24b4c3c04f47.png"></a>
 
The end result is almost indistinguishable, but I think it'll be less likely to cause blurry-edge/hinting issues. Other than that, I say 🚢 it!

**Review by iamthomasbishop — CHANGES_REQUESTED** [review]
Looks great overall @SylvesterWilmott! One tiny suggestion: I think we might be able to get the "pencil" part of the icon aligned more tightly to the gridlines, like so (current icon left, and on the left is refined to the 2px gridline):

<a href="https://user-images.githubusercontent.com/1200432/123008562-b3c15a80-d380-11eb-850f-24b4c3c04f47.png"></a>
 
The end result is almost indistinguishable, but I think it'll be less likely to cause blurry-edge/hinting issues. Other than that, I say 🚢 it!

**Comment by SylvesterWilmott** [comment]
Thanks for the in-depth review @iamthomasbishop!

The alignment thing you noticed was a result of rotating the "pencil" around an axis that matches the outer edge of the "paper" centered on the middle of the stroke on the pencil, see below for illustration.

Screenshot 2021-06-23 at 09 22 11

The slight protrusion of the pencil from the paper does already cause a slight shift of the visual center but I found that anything exceeding what's shown above makes it very noticeable which is what we want to avoid. See below for illustration.

Screenshot 2021-06-23 at 09 34 05

left: original, right: 2px from container edge

I tried chopping it the other way too so that instead of the pencil being 2px away from the container, it's 3. But I think this lowers the overall perceived size of the icon without really doing **that** much to improve the visual center.

Screenshot 2021-06-23 at 09 36 54

Let me know what you think.

**Comment by SylvesterWilmott** [comment]
Thanks for the in-depth review @iamthomasbishop!

The pencil is rotated around the axis of the outer edge of the path for the paper so that the pencil protrudes from the paper by a marginal amount. I found that exceeding this, shifted the visual center noticeably which is what we are trying to avoid. 

I tried rotating the pencil around the point instead and aligning the edges 3px from the container instead of 2. I think this produces an icon with a visual center that is closer to the true center while preserving the percieved size of the icon overall. Let me know what you think.

Screenshot 2021-06-23 at 10 45 30

**Comment by iamthomasbishop** [comment]
Ah, good points and that looks great. Going to merge! 🚀

**Pull request merged**
